baseurl = "https://rambling-dev.gitlab.io/blog"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "rambling-dev"
canonifyurls  = true

DefaultContentLanguage = "en"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "rambling-dev blog"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Rambling Dev"
  email = "ramblingdev@gmail.com"
  facebook = "username"
  gitlab = "rambling-dev"
  github = "rambling-dev"
  twitter = "username"
  linkedin = "username"
  stackoverflow = "users/XXXXXXX/username"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3


